// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"lawmatics-pp-cli/internal/cli"
	"lawmatics-pp-cli/internal/client"
	"lawmatics-pp-cli/internal/cliutil"
	"lawmatics-pp-cli/internal/config"
	"lawmatics-pp-cli/internal/mcp/cobratree"
	"lawmatics-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("addresses_create",
			mcplib.WithDescription("Create an address. Optional: street."),
			mcplib.WithString("street", mcplib.Description("Street")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/addresses", false, []mcpParamBinding{{PublicName: "street", WireName: "street", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("addresses_delete",
			mcplib.WithDescription("Delete an address. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/addresses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("addresses_get",
			mcplib.WithDescription("Get an address. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/addresses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("addresses_list",
			mcplib.WithDescription("List addresses. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/addresses", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("addresses_update",
			mcplib.WithDescription("Update an address. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/addresses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("comments_create",
			mcplib.WithDescription("Create a comment. Optional: body."),
			mcplib.WithString("body", mcplib.Description("Body")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/comments", false, []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("comments_delete",
			mcplib.WithDescription("Delete a comment. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/comments/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("comments_get",
			mcplib.WithDescription("Get a comment. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/comments/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("comments_list",
			mcplib.WithDescription("List comments. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/comments", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("comments_update",
			mcplib.WithDescription("Update a comment. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/comments/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_create",
			mcplib.WithDescription("Create a new company. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Company name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/companies", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_delete",
			mcplib.WithDescription("Delete a company. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The company identifier")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/companies/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_find_by_email",
			mcplib.WithDescription("Find a company by email. Required: email."),
			mcplib.WithString("email", mcplib.Required(), mcplib.Description("Email")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companies/find_by_email", false, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_find_by_name",
			mcplib.WithDescription("Find a company by name. Required: name."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Company name")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companies/find_by_name", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_find_by_phone",
			mcplib.WithDescription("Find a company by phone. Required: phone."),
			mcplib.WithString("phone", mcplib.Required(), mcplib.Description("Phone")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companies/find_by_phone", false, []mcpParamBinding{{PublicName: "phone", WireName: "phone", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_get",
			mcplib.WithDescription("Get a company by ID. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The company identifier")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companies/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_list",
			mcplib.WithDescription("List all companies. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companies", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_update",
			mcplib.WithDescription("Update a company. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The company identifier")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/companies/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("contacts_create",
			mcplib.WithDescription("Create a new contact. Optional: first_name, last_name, email."),
			mcplib.WithString("first_name", mcplib.Description("First name")),
			mcplib.WithString("last_name", mcplib.Description("Last name")),
			mcplib.WithString("email", mcplib.Description("Email address")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/contacts", false, []mcpParamBinding{{PublicName: "first_name", WireName: "first_name", Location: "body"}, {PublicName: "last_name", WireName: "last_name", Location: "body"}, {PublicName: "email", WireName: "email", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contacts_delete",
			mcplib.WithDescription("Delete a contact. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The contact identifier")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/contacts/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("contacts_find_by_email",
			mcplib.WithDescription("Find a contact by email. Required: email."),
			mcplib.WithString("email", mcplib.Required(), mcplib.Description("Email address")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts/find_by_email", false, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contacts_find_by_name",
			mcplib.WithDescription("Find a contact by name. Required: name."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts/find_by_name", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contacts_find_by_phone",
			mcplib.WithDescription("Find a contact by phone. Required: phone."),
			mcplib.WithString("phone", mcplib.Required(), mcplib.Description("Phone number")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts/find_by_phone", false, []mcpParamBinding{{PublicName: "phone", WireName: "phone", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contacts_get",
			mcplib.WithDescription("Get a contact by ID. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The contact identifier")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("contacts_list",
			mcplib.WithDescription("List all contacts. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contacts_update",
			mcplib.WithDescription("Update a contact. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The contact identifier")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/contacts/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("custom_contact_types_create",
			mcplib.WithDescription("Create a custom contact type. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/custom_contact_types", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("custom_contact_types_delete",
			mcplib.WithDescription("Delete a custom contact type. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/custom_contact_types/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("custom_contact_types_get",
			mcplib.WithDescription("Get a custom contact type. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/custom_contact_types/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("custom_contact_types_list",
			mcplib.WithDescription("List custom contact types. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/custom_contact_types", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("custom_contact_types_update",
			mcplib.WithDescription("Update a custom contact type. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/custom_contact_types/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("custom_fields_create",
			mcplib.WithDescription("Create a custom field. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/custom_fields", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("custom_fields_delete",
			mcplib.WithDescription("Delete a custom field. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/custom_fields/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("custom_fields_get",
			mcplib.WithDescription("Get a custom field. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/custom_fields/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("custom_fields_list",
			mcplib.WithDescription("List custom fields. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/custom_fields", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("custom_fields_update",
			mcplib.WithDescription("Update a custom field. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/custom_fields/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("email_addresses_create",
			mcplib.WithDescription("Create an email address. Optional: email."),
			mcplib.WithString("email", mcplib.Description("Email")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/email_addresses", false, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("email_addresses_delete",
			mcplib.WithDescription("Delete an email address. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/email_addresses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("email_addresses_get",
			mcplib.WithDescription("Get an email address. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/email_addresses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("email_addresses_list",
			mcplib.WithDescription("List email addresses. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/email_addresses", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("email_addresses_update",
			mcplib.WithDescription("Update an email address. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/email_addresses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("email_campaigns_get",
			mcplib.WithDescription("Get an email campaign. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/email_campaigns/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("email_campaigns_list",
			mcplib.WithDescription("List email campaigns. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/email_campaigns", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("email_campaigns_stats",
			mcplib.WithDescription("Get email campaign stats. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/email_campaigns/{id}/stats", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("event_types_create",
			mcplib.WithDescription("Create an event type. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/event_types", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("event_types_delete",
			mcplib.WithDescription("Delete an event type. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/event_types/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("event_types_get",
			mcplib.WithDescription("Get an event type. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/event_types/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("event_types_list",
			mcplib.WithDescription("List event types. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/event_types", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("event_types_update",
			mcplib.WithDescription("Update an event type. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/event_types/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("events_create",
			mcplib.WithDescription("Create an event. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/events", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("events_delete",
			mcplib.WithDescription("Delete an event. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/events/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("events_get",
			mcplib.WithDescription("Get an event. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/events/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("events_list",
			mcplib.WithDescription("List events. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/events", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("expenses_create",
			mcplib.WithDescription("Create an expense. Optional: amount."),
			mcplib.WithNumber("amount", mcplib.Description("Amount")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/expenses", false, []mcpParamBinding{{PublicName: "amount", WireName: "amount", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("expenses_delete",
			mcplib.WithDescription("Delete an expense. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/expenses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("expenses_get",
			mcplib.WithDescription("Get an expense. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/expenses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("expenses_list",
			mcplib.WithDescription("List expenses. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/expenses", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("expenses_update",
			mcplib.WithDescription("Update an expense. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/expenses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("files_delete",
			mcplib.WithDescription("Delete a file. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/files/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("files_download",
			mcplib.WithDescription("Download a file. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files/{id}/download", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("files_get",
			mcplib.WithDescription("Get a file. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("files_list",
			mcplib.WithDescription("List files. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("files_update",
			mcplib.WithDescription("Update a file. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/files/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("files_upload",
			mcplib.WithDescription("Upload a file. Optional: file."),
			mcplib.WithString("file", mcplib.Description("File data")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/files", false, []mcpParamBinding{{PublicName: "file", WireName: "file", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("folders_create",
			mcplib.WithDescription("Create a folder. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/folders", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("folders_delete",
			mcplib.WithDescription("Delete a folder. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/folders/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("folders_get",
			mcplib.WithDescription("Get a folder. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/folders/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("folders_list",
			mcplib.WithDescription("List folders. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/folders", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("folders_update",
			mcplib.WithDescription("Update a folder. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/folders/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("interactions_create",
			mcplib.WithDescription("Create an interaction. Optional: body."),
			mcplib.WithString("body", mcplib.Description("Body")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/interactions", false, []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("interactions_delete",
			mcplib.WithDescription("Delete an interaction. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/interactions/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("interactions_get",
			mcplib.WithDescription("Get an interaction. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/interactions/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("interactions_list",
			mcplib.WithDescription("List interactions. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/interactions", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("interactions_update",
			mcplib.WithDescription("Update an interaction. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/interactions/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("invoices_get",
			mcplib.WithDescription("Get an invoice. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/invoices/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("invoices_list",
			mcplib.WithDescription("List invoices. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/invoices", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("locations_list",
			mcplib.WithDescription("List locations. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/locations", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("matter_sub_statuses_create",
			mcplib.WithDescription("Create a matter sub status. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/matter_sub_statuses", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("matter_sub_statuses_delete",
			mcplib.WithDescription("Delete a matter sub status. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The sub status identifier")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/matter_sub_statuses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("matter_sub_statuses_update",
			mcplib.WithDescription("Update a matter sub status. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The sub status identifier")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/matter_sub_statuses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("matters_create",
			mcplib.WithDescription("Create a new matter. Optional: contact_id, company_id, company_name (plus 1 more)."),
			mcplib.WithString("contact_id", mcplib.Description("Contact ID")),
			mcplib.WithString("company_id", mcplib.Description("Company ID")),
			mcplib.WithString("company_name", mcplib.Description("Company name")),
			mcplib.WithString("match_contact_by", mcplib.Description("Match contact by field")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/matters", false, []mcpParamBinding{{PublicName: "contact_id", WireName: "contact_id", Location: "body"}, {PublicName: "company_id", WireName: "company_id", Location: "body"}, {PublicName: "company_name", WireName: "company_name", Location: "body"}, {PublicName: "match_contact_by", WireName: "match_contact_by", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("matters_delete",
			mcplib.WithDescription("Delete a matter. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The matter identifier")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/matters/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("matters_find_by_email",
			mcplib.WithDescription("Find a matter by email. Required: email."),
			mcplib.WithString("email", mcplib.Required(), mcplib.Description("Email")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/matters/find_by_email", false, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("matters_get",
			mcplib.WithDescription("Get a matter by ID. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The matter identifier")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/matters/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("matters_list",
			mcplib.WithDescription("List all matters. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/matters", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("matters_update",
			mcplib.WithDescription("Update a matter. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The matter identifier")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/matters/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("notes_create",
			mcplib.WithDescription("Create a note. Optional: body."),
			mcplib.WithString("body", mcplib.Description("Body")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/notes", false, []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("notes_delete",
			mcplib.WithDescription("Delete a note. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/notes/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("notes_get",
			mcplib.WithDescription("Get a note. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/notes/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("notes_list",
			mcplib.WithDescription("List notes. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/notes", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("notes_update",
			mcplib.WithDescription("Update a note. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/notes/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("phone_numbers_create",
			mcplib.WithDescription("Create a phone number. Optional: number."),
			mcplib.WithString("number", mcplib.Description("Phone number")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/phone_numbers", false, []mcpParamBinding{{PublicName: "number", WireName: "number", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("phone_numbers_delete",
			mcplib.WithDescription("Delete a phone number. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/phone_numbers/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("phone_numbers_get",
			mcplib.WithDescription("Get a phone number. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/phone_numbers/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("phone_numbers_list",
			mcplib.WithDescription("List phone numbers. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/phone_numbers", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("phone_numbers_update",
			mcplib.WithDescription("Update a phone number. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/phone_numbers/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("pipelines_get",
			mcplib.WithDescription("Get a pipeline by ID. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The pipeline identifier")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/pipelines/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("pipelines_list",
			mcplib.WithDescription("List pipelines. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/pipelines", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("practice_areas_create",
			mcplib.WithDescription("Create a practice area. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/practice_areas", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("practice_areas_delete",
			mcplib.WithDescription("Delete a practice area. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/practice_areas/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("practice_areas_get",
			mcplib.WithDescription("Get a practice area. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/practice_areas/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("practice_areas_list",
			mcplib.WithDescription("List practice areas. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/practice_areas", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("practice_areas_update",
			mcplib.WithDescription("Update a practice area. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/practice_areas/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("prospects_create",
			mcplib.WithDescription("Create a prospect. Optional: first_name, last_name."),
			mcplib.WithString("first_name", mcplib.Description("First name")),
			mcplib.WithString("last_name", mcplib.Description("Last name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/prospects", false, []mcpParamBinding{{PublicName: "first_name", WireName: "first_name", Location: "body"}, {PublicName: "last_name", WireName: "last_name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("prospects_delete",
			mcplib.WithDescription("Delete a prospect. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The prospect identifier")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/prospects/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("prospects_get",
			mcplib.WithDescription("Get a prospect. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The prospect identifier")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/prospects/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("prospects_list",
			mcplib.WithDescription("List prospects. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/prospects", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("prospects_update",
			mcplib.WithDescription("Update a prospect. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The prospect identifier")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/prospects/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("relationship_types_create",
			mcplib.WithDescription("Create a relationship type. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/relationship_types", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("relationship_types_get",
			mcplib.WithDescription("Get a relationship type. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/relationship_types/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("relationship_types_list",
			mcplib.WithDescription("List relationship types. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/relationship_types", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("relationship_types_update",
			mcplib.WithDescription("Update a relationship type. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/relationship_types/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("relationships_create",
			mcplib.WithDescription("Create a relationship. Optional: relationship_type_id."),
			mcplib.WithString("relationship_type_id", mcplib.Description("Type id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/relationships", false, []mcpParamBinding{{PublicName: "relationship_type_id", WireName: "relationship_type_id", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("relationships_delete",
			mcplib.WithDescription("Delete a relationship. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/relationships/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("relationships_get",
			mcplib.WithDescription("Get a relationship. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/relationships/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("relationships_list",
			mcplib.WithDescription("List relationships. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/relationships", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("relationships_update",
			mcplib.WithDescription("Update a relationship. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/relationships/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("stages_get",
			mcplib.WithDescription("Get a stage. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The stage identifier")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stages/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("stages_list",
			mcplib.WithDescription("List stages. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stages", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("subtasks_create",
			mcplib.WithDescription("Create a subtask. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/subtasks", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("subtasks_delete",
			mcplib.WithDescription("Delete a subtask. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/subtasks/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("subtasks_get",
			mcplib.WithDescription("Get a subtask. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/subtasks/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("subtasks_list",
			mcplib.WithDescription("List subtasks. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/subtasks", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("subtasks_update",
			mcplib.WithDescription("Update a subtask. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/subtasks/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("tags_create",
			mcplib.WithDescription("Create a tag. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/tags", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tags_delete",
			mcplib.WithDescription("Delete a tag. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/tags/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("tags_get",
			mcplib.WithDescription("Get a tag. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tags/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("tags_list",
			mcplib.WithDescription("List tags. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tags", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tags_update",
			mcplib.WithDescription("Update a tag. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/tags/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("task_statuses_create",
			mcplib.WithDescription("Create a task status. Optional: name."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/task_statuses", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("task_statuses_delete",
			mcplib.WithDescription("Delete a task status. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/task_statuses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("task_statuses_get",
			mcplib.WithDescription("Get a task status. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/task_statuses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("task_statuses_list",
			mcplib.WithDescription("List task statuses. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/task_statuses", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("task_statuses_update",
			mcplib.WithDescription("Update a task status. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/task_statuses/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("tasks_create",
			mcplib.WithDescription("Create a task. Optional: name, assigned_by_id, recurrence_rule."),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithString("assigned_by_id", mcplib.Description("Assigned by user id")),
			mcplib.WithString("recurrence_rule", mcplib.Description("Recurrence rule")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/tasks", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "assigned_by_id", WireName: "assigned_by_id", Location: "body"}, {PublicName: "recurrence_rule", WireName: "recurrence_rule", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tasks_delete",
			mcplib.WithDescription("Delete a task. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/tasks/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("tasks_get",
			mcplib.WithDescription("Get a task. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tasks/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("tasks_list",
			mcplib.WithDescription("List tasks. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tasks", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tasks_update",
			mcplib.WithDescription("Update a task. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/tasks/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("time_entries_create",
			mcplib.WithDescription("Create a time entry. Optional: duration."),
			mcplib.WithNumber("duration", mcplib.Description("Duration")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/time_entries", false, []mcpParamBinding{{PublicName: "duration", WireName: "duration", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("time_entries_delete",
			mcplib.WithDescription("Delete a time entry. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/time_entries/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("time_entries_get",
			mcplib.WithDescription("Get a time entry. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/time_entries/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("time_entries_list",
			mcplib.WithDescription("List time entries. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/time_entries", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("time_entries_update",
			mcplib.WithDescription("Update a time entry. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/time_entries/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("transactions_create",
			mcplib.WithDescription("Create a transaction. Optional: amount."),
			mcplib.WithNumber("amount", mcplib.Description("Amount")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/transactions", false, []mcpParamBinding{{PublicName: "amount", WireName: "amount", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("transactions_get",
			mcplib.WithDescription("Get a transaction. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/transactions/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("transactions_list",
			mcplib.WithDescription("List transactions. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/transactions", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users_create",
			mcplib.WithDescription("Create a user. Optional: email."),
			mcplib.WithString("email", mcplib.Description("Email")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/users", false, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users_delete",
			mcplib.WithDescription("Delete a user. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/users/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("users_get",
			mcplib.WithDescription("Get a user. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/users/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("users_list",
			mcplib.WithDescription("List users. Returns array."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/users", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users_update",
			mcplib.WithDescription("Update a user. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/users/{id}", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export LAWMATICS_ACCESS_TOKEN=<your-key>" +
					"\n      Run 'lawmatics-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your token may have expired. Re-run 'lawmatics-pp-cli auth login' to re-authenticate" +
					"\n      Set it with: export LAWMATICS_ACCESS_TOKEN=<your-key>" +
					"\n      Run 'lawmatics-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your token may lack required scopes. Re-run 'lawmatics-pp-cli auth login' to re-authorize" +
					"\n      Set it with: export LAWMATICS_ACCESS_TOKEN=<your-key>" +
					"\n      Run 'lawmatics-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "lawmatics-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "lawmatics-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "lawmatics",
		"description": "Every Lawmatics resource the API exposes, plus offline full-text search, custom-field reports, and intake analytics...",
		"archetype":   "crm",
		"tool_count":  152,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion lawmatics-pp-cli binary.",
		"auth": map[string]any{
			"type": "oauth2",
			"env_vars": []map[string]any{
				{
					"name":        "LAWMATICS_ACCESS_TOKEN",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "addresses",
				"description": "Operations on addresses",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "comments",
				"description": "Operations on comments",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "companies",
				"description": "Operations on companies",
				"endpoints":   []string{"create", "delete", "find_by_email", "find_by_name", "find_by_phone", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "contacts",
				"description": "Operations on contacts",
				"endpoints":   []string{"create", "delete", "find_by_email", "find_by_name", "find_by_phone", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "custom_contact_types",
				"description": "Operations on custom contact types",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "custom_fields",
				"description": "Operations on custom fields",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "email_addresses",
				"description": "Operations on email addresses",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "email_campaigns",
				"description": "Operations on email campaigns",
				"endpoints":   []string{"get", "list", "stats"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "event_types",
				"description": "Operations on event types",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "events",
				"description": "Operations on events",
				"endpoints":   []string{"create", "delete", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "expenses",
				"description": "Operations on expenses",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "files",
				"description": "Operations on files",
				"endpoints":   []string{"delete", "download", "get", "list", "update", "upload"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "folders",
				"description": "Operations on folders",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "interactions",
				"description": "Operations on interactions",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "invoices",
				"description": "Operations on invoices",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "locations",
				"description": "Operations on locations",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
			{
				"name":        "matter_sub_statuses",
				"description": "Operations on matter sub statuses",
				"endpoints":   []string{"create", "delete", "update"},
				"searchable":  true,
			},
			{
				"name":        "matters",
				"description": "Operations on matters",
				"endpoints":   []string{"create", "delete", "find_by_email", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "notes",
				"description": "Operations on notes",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "phone_numbers",
				"description": "Operations on phone numbers",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "pipelines",
				"description": "Operations on pipelines",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "practice_areas",
				"description": "Operations on practice areas",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "prospects",
				"description": "Operations on prospects",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "relationship_types",
				"description": "Operations on relationship types",
				"endpoints":   []string{"create", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "relationships",
				"description": "Operations on relationships",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "stages",
				"description": "Operations on stages",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "subtasks",
				"description": "Operations on subtasks",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "tags",
				"description": "Operations on tags",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "task_statuses",
				"description": "Operations on task statuses",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "tasks",
				"description": "Operations on tasks",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "time_entries",
				"description": "Operations on time entries",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "transactions",
				"description": "Operations on transactions",
				"endpoints":   []string{"create", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "users",
				"description": "Operations on users",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Local SQLite mirror + FTS5", "command": "search", "description": "Sub-100ms offline full-text search across contacts, matters, notes, comments, and interactions including custom fields.", "rationale": "Requires a local relational mirror; the API exposes no cross-resource search.", "via": "mcp-command-mirror"},
			{"name": "Stage bottleneck", "command": "bottleneck", "description": "Median matter dwell-time per intake/pipeline stage, surfacing where deals get stuck.", "rationale": "Needs local join across matters, stages, and activity history; no upstream aggregation.", "via": "mcp-command-mirror"},
			{"name": "Cross-matter overdue", "command": "overdue", "description": "Every past-due task across every matter, grouped by assignee and sorted by lateness.", "rationale": "Requires aggregating tasks across all matters; no single API endpoint provides this.", "via": "mcp-command-mirror"},
			{"name": "Since-window change feed", "command": "since", "description": "Everything created or updated in the last N hours/days across all entities.", "rationale": "Time-windowed aggregation across many resources; needs cursor history.", "via": "mcp-command-mirror"},
			{"name": "Custom-field report", "command": "cf report", "description": "Join contacts and matters with arbitrary custom fields and pivot to CSV/JSON.", "rationale": "Lawmatics UI cannot pivot custom fields across resources; requires local join.", "via": "mcp-command-mirror"},
			{"name": "Bulk reassign", "command": "bulk reassign", "description": "Reassign every task matching a filter from one user to another in one command.", "rationale": "Filter-driven bulk write; the web UI requires per-task clicks.", "via": "mcp-command-mirror"},
			{"name": "Source velocity", "command": "velocity", "description": "Rolling conversion rate (prospect to signed matter) per referral source with sparklines.", "rationale": "Requires historical snapshots; needs local store.", "via": "mcp-command-mirror"},
			{"name": "Stale intake", "command": "intake stale", "description": "Prospects with zero interactions in N days.", "rationale": "Requires cross-resource aggregation (prospects join interactions); web filters can't express it.", "via": "mcp-command-mirror"},
			{"name": "Who-touched", "command": "who-touched", "description": "Unified chronological feed of every interaction, note, task, and email across all matters for a contact.", "rationale": "Reconstructs the full client relationship from many small endpoints.", "via": "mcp-command-mirror"},
			{"name": "Revenue by source", "command": "revenue", "description": "Sums invoiced and paid amounts per referral source or practice area.", "rationale": "Cross-resource aggregation (invoices join matters join sources).", "via": "mcp-command-mirror"},
			{"name": "Attorney load", "command": "load", "description": "Open matters, overdue tasks, and billable hours MTD per attorney.", "rationale": "Cross-resource aggregation no single endpoint exposes.", "via": "mcp-command-mirror"},
			{"name": "Doctor", "command": "doctor", "description": "Health check: orphan tasks, contacts with no email, matters in dead stages, custom fields never used, dormant users.", "rationale": "Aggregate quality check across resources.", "via": "mcp-command-mirror"},
			{"name": "Webhook bridge", "command": "watch", "description": "Local daemon that polls and POSTs entity diffs to a URL of your choice.", "rationale": "Substitute for orgs that don't have a Lawmatics webhook plan.", "via": "mcp-command-mirror"},
			{"name": "Matter explain", "command": "explain", "description": "Markdown brief summarizing a matter from notes, interactions, and tasks.", "rationale": "Composite summary requires reading many small endpoints.", "via": "mcp-command-mirror"},
			{"name": "Pipeline drift", "command": "pipeline drift", "description": "Matters that skipped a stage or moved backward through the pipeline.", "rationale": "Process-violation detector requires stage transition history.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Local SQLite mirror + FTS5", "insight": "Requires a local relational mirror; the API exposes no cross-resource search."},
			{"topic": "Stage bottleneck", "insight": "Needs local join across matters, stages, and activity history; no upstream aggregation."},
			{"topic": "Cross-matter overdue", "insight": "Requires aggregating tasks across all matters; no single API endpoint provides this."},
			{"topic": "Since-window change feed", "insight": "Time-windowed aggregation across many resources; needs cursor history."},
			{"topic": "Custom-field report", "insight": "Lawmatics UI cannot pivot custom fields across resources; requires local join."},
			{"topic": "Bulk reassign", "insight": "Filter-driven bulk write; the web UI requires per-task clicks."},
			{"topic": "Source velocity", "insight": "Requires historical snapshots; needs local store."},
			{"topic": "Stale intake", "insight": "Requires cross-resource aggregation (prospects join interactions); web filters can't express it."},
			{"topic": "Who-touched", "insight": "Reconstructs the full client relationship from many small endpoints."},
			{"topic": "Revenue by source", "insight": "Cross-resource aggregation (invoices join matters join sources)."},
			{"topic": "Attorney load", "insight": "Cross-resource aggregation no single endpoint exposes."},
			{"topic": "Doctor", "insight": "Aggregate quality check across resources."},
			{"topic": "Webhook bridge", "insight": "Substitute for orgs that don't have a Lawmatics webhook plan."},
			{"topic": "Matter explain", "insight": "Composite summary requires reading many small endpoints."},
			{"topic": "Pipeline drift", "insight": "Process-violation detector requires stage transition history."},
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
