// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAddressesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "addresses",
		Short:  "Operations on addresses",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAddressesCreateCmd(flags))
	cmd.AddCommand(newAddressesDeleteCmd(flags))
	cmd.AddCommand(newAddressesGetCmd(flags))
	cmd.AddCommand(newAddressesListCmd(flags))
	cmd.AddCommand(newAddressesUpdateCmd(flags))
	return cmd
}
