// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCompaniesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "companies",
		Short:  "Operations on companies",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCompaniesCreateCmd(flags))
	cmd.AddCommand(newCompaniesDeleteCmd(flags))
	cmd.AddCommand(newCompaniesFindByEmailCmd(flags))
	cmd.AddCommand(newCompaniesFindByNameCmd(flags))
	cmd.AddCommand(newCompaniesFindByPhoneCmd(flags))
	cmd.AddCommand(newCompaniesGetCmd(flags))
	cmd.AddCommand(newCompaniesListCmd(flags))
	cmd.AddCommand(newCompaniesUpdateCmd(flags))
	return cmd
}
