// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCustomFieldsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "custom-fields",
		Short:  "Operations on custom fields",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCustomFieldsCreateCmd(flags))
	cmd.AddCommand(newCustomFieldsDeleteCmd(flags))
	cmd.AddCommand(newCustomFieldsGetCmd(flags))
	cmd.AddCommand(newCustomFieldsListCmd(flags))
	cmd.AddCommand(newCustomFieldsUpdateCmd(flags))
	return cmd
}
