// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCustomContactTypesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "custom-contact-types",
		Short:  "Operations on custom contact types",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCustomContactTypesCreateCmd(flags))
	cmd.AddCommand(newCustomContactTypesDeleteCmd(flags))
	cmd.AddCommand(newCustomContactTypesGetCmd(flags))
	cmd.AddCommand(newCustomContactTypesListCmd(flags))
	cmd.AddCommand(newCustomContactTypesUpdateCmd(flags))
	return cmd
}
