// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEmailAddressesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "email-addresses",
		Short:  "Operations on email addresses",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEmailAddressesCreateCmd(flags))
	cmd.AddCommand(newEmailAddressesDeleteCmd(flags))
	cmd.AddCommand(newEmailAddressesGetCmd(flags))
	cmd.AddCommand(newEmailAddressesListCmd(flags))
	cmd.AddCommand(newEmailAddressesUpdateCmd(flags))
	return cmd
}
