// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEmailCampaignsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "email-campaigns",
		Short:  "Operations on email campaigns",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEmailCampaignsGetCmd(flags))
	cmd.AddCommand(newEmailCampaignsListCmd(flags))
	cmd.AddCommand(newEmailCampaignsStatsCmd(flags))
	return cmd
}
