// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEventTypesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "event-types",
		Short:  "Operations on event types",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEventTypesCreateCmd(flags))
	cmd.AddCommand(newEventTypesDeleteCmd(flags))
	cmd.AddCommand(newEventTypesGetCmd(flags))
	cmd.AddCommand(newEventTypesListCmd(flags))
	cmd.AddCommand(newEventTypesUpdateCmd(flags))
	return cmd
}
