// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newExpensesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "expenses",
		Short:  "Operations on expenses",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newExpensesCreateCmd(flags))
	cmd.AddCommand(newExpensesDeleteCmd(flags))
	cmd.AddCommand(newExpensesGetCmd(flags))
	cmd.AddCommand(newExpensesListCmd(flags))
	cmd.AddCommand(newExpensesUpdateCmd(flags))
	return cmd
}
