// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

func newExportCmd(flags *rootFlags) *cobra.Command {
	var format string
	var outputFile string
	var limit int
	var noCache bool

	cmd := &cobra.Command{
		Use:   "export <resource> [id]",
		Short: "Export data to JSONL or JSON for backup, migration, or analysis",
		Long: `Export paginated API data to a local file. Supports JSONL (one JSON object
per line, streaming-friendly) and JSON (array). JSONL is recommended for
large datasets as it has no memory pressure.`,
		Example: `  # Export all items as JSONL (streaming, recommended for large datasets)
  lawmatics-pp-cli export <resource> --format jsonl --output data.jsonl

  # Export with limit
  lawmatics-pp-cli export <resource> --format jsonl --limit 1000

  # Pipe to another tool
  lawmatics-pp-cli export <resource> --format jsonl | jq '.id'`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			validResources := map[string]bool{
				"addresses":            true,
				"comments":             true,
				"companies":            true,
				"contacts":             true,
				"custom_contact_types": true,
				"custom_fields":        true,
				"email_addresses":      true,
				"email_campaigns":      true,
				"event_types":          true,
				"events":               true,
				"expenses":             true,
				"files":                true,
				"folders":              true,
				"interactions":         true,
				"invoices":             true,
				"locations":            true,
				"matters":              true,
				"notes":                true,
				"phone_numbers":        true,
				"pipelines":            true,
				"practice_areas":       true,
				"prospects":            true,
				"relationship_types":   true,
				"relationships":        true,
				"stages":               true,
				"subtasks":             true,
				"tags":                 true,
				"task_statuses":        true,
				"tasks":                true,
				"time_entries":         true,
				"transactions":         true,
				"users":                true,
			}
			validResourceList := []string{
				"addresses",
				"comments",
				"companies",
				"contacts",
				"custom_contact_types",
				"custom_fields",
				"email_addresses",
				"email_campaigns",
				"event_types",
				"events",
				"expenses",
				"files",
				"folders",
				"interactions",
				"invoices",
				"locations",
				"matters",
				"notes",
				"phone_numbers",
				"pipelines",
				"practice_areas",
				"prospects",
				"relationship_types",
				"relationships",
				"stages",
				"subtasks",
				"tags",
				"task_statuses",
				"tasks",
				"time_entries",
				"transactions",
				"users",
			}
			resource := args[0]
			if !validResources[resource] {
				return usageErr(fmt.Errorf("unknown resource %q; valid: %s", resource, strings.Join(validResourceList, ", ")))
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}
			if noCache {
				c.NoCache = true
			}

			path := "/" + resource
			if len(args) > 1 {
				path += "/" + args[1]
			}

			var writer *bufio.Writer
			if outputFile != "" {
				f, err := os.Create(outputFile)
				if err != nil {
					return fmt.Errorf("creating output file: %w", err)
				}
				defer f.Close()
				writer = bufio.NewWriter(f)
				defer writer.Flush()
			} else {
				writer = bufio.NewWriter(os.Stdout)
				defer writer.Flush()
			}

			data, err := c.Get(path, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}

			switch format {
			case "jsonl":
				var items []json.RawMessage
				if err := json.Unmarshal(data, &items); err != nil {
					fmt.Fprintln(writer, string(data))
					return nil
				}
				count := 0
				for _, item := range items {
					if limit > 0 && count >= limit {
						break
					}
					fmt.Fprintln(writer, string(item))
					count++
				}
				if outputFile != "" {
					fmt.Fprintf(os.Stderr, "Exported %d records to %s\n", count, outputFile)
				}
			default:
				enc := json.NewEncoder(writer)
				enc.SetIndent("", "  ")
				var parsed any
				if err := json.Unmarshal(data, &parsed); err != nil {
					return err
				}
				return enc.Encode(parsed)
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&format, "format", "jsonl", "Output format: jsonl or json")
	cmd.Flags().StringVarP(&outputFile, "output", "o", "", "Output file path (default: stdout)")
	cmd.Flags().IntVar(&limit, "limit", 0, "Maximum records to export (0 = unlimited)")
	cmd.Flags().BoolVar(&noCache, "no-cache", false, "Bypass response cache for fresh data")

	return cmd
}
