// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "files",
		Short:  "Operations on files",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFilesDeleteCmd(flags))
	cmd.AddCommand(newFilesDownloadCmd(flags))
	cmd.AddCommand(newFilesGetCmd(flags))
	cmd.AddCommand(newFilesListCmd(flags))
	cmd.AddCommand(newFilesUpdateCmd(flags))
	cmd.AddCommand(newFilesUploadCmd(flags))
	return cmd
}
