// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFoldersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "folders",
		Short:  "Operations on folders",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFoldersCreateCmd(flags))
	cmd.AddCommand(newFoldersDeleteCmd(flags))
	cmd.AddCommand(newFoldersGetCmd(flags))
	cmd.AddCommand(newFoldersListCmd(flags))
	cmd.AddCommand(newFoldersUpdateCmd(flags))
	return cmd
}
