// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInteractionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "interactions",
		Short:  "Operations on interactions",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInteractionsCreateCmd(flags))
	cmd.AddCommand(newInteractionsDeleteCmd(flags))
	cmd.AddCommand(newInteractionsGetCmd(flags))
	cmd.AddCommand(newInteractionsListCmd(flags))
	cmd.AddCommand(newInteractionsUpdateCmd(flags))
	return cmd
}
