// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInvoicesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "invoices",
		Short:  "Operations on invoices",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInvoicesGetCmd(flags))
	cmd.AddCommand(newInvoicesListCmd(flags))
	return cmd
}
