// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMatterSubStatusesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "matter-sub-statuses",
		Short:  "Operations on matter sub statuses",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMatterSubStatusesCreateCmd(flags))
	cmd.AddCommand(newMatterSubStatusesDeleteCmd(flags))
	cmd.AddCommand(newMatterSubStatusesUpdateCmd(flags))
	return cmd
}
