// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMattersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "matters",
		Short:  "Operations on matters",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMattersCreateCmd(flags))
	cmd.AddCommand(newMattersDeleteCmd(flags))
	cmd.AddCommand(newMattersFindByEmailCmd(flags))
	cmd.AddCommand(newMattersGetCmd(flags))
	cmd.AddCommand(newMattersListCmd(flags))
	cmd.AddCommand(newMattersUpdateCmd(flags))
	return cmd
}
