// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPhoneNumbersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "phone-numbers",
		Short:  "Operations on phone numbers",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPhoneNumbersCreateCmd(flags))
	cmd.AddCommand(newPhoneNumbersDeleteCmd(flags))
	cmd.AddCommand(newPhoneNumbersGetCmd(flags))
	cmd.AddCommand(newPhoneNumbersListCmd(flags))
	cmd.AddCommand(newPhoneNumbersUpdateCmd(flags))
	return cmd
}
