// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPipelinesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "pipelines",
		Short:  "Operations on pipelines",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPipelinesGetCmd(flags))
	cmd.AddCommand(newPipelinesListCmd(flags))
	return cmd
}
