// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPracticeAreasCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "practice-areas",
		Short:  "Operations on practice areas",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPracticeAreasCreateCmd(flags))
	cmd.AddCommand(newPracticeAreasDeleteCmd(flags))
	cmd.AddCommand(newPracticeAreasGetCmd(flags))
	cmd.AddCommand(newPracticeAreasListCmd(flags))
	cmd.AddCommand(newPracticeAreasUpdateCmd(flags))
	return cmd
}
