// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProspectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "prospects",
		Short:  "Operations on prospects",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProspectsCreateCmd(flags))
	cmd.AddCommand(newProspectsDeleteCmd(flags))
	cmd.AddCommand(newProspectsGetCmd(flags))
	cmd.AddCommand(newProspectsListCmd(flags))
	cmd.AddCommand(newProspectsUpdateCmd(flags))
	return cmd
}
