// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRelationshipTypesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "relationship-types",
		Short:  "Operations on relationship types",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRelationshipTypesCreateCmd(flags))
	cmd.AddCommand(newRelationshipTypesGetCmd(flags))
	cmd.AddCommand(newRelationshipTypesListCmd(flags))
	cmd.AddCommand(newRelationshipTypesUpdateCmd(flags))
	return cmd
}
