// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRelationshipsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "relationships",
		Short:  "Operations on relationships",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRelationshipsCreateCmd(flags))
	cmd.AddCommand(newRelationshipsDeleteCmd(flags))
	cmd.AddCommand(newRelationshipsGetCmd(flags))
	cmd.AddCommand(newRelationshipsListCmd(flags))
	cmd.AddCommand(newRelationshipsUpdateCmd(flags))
	return cmd
}
