// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSubtasksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "subtasks",
		Short:  "Operations on subtasks",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSubtasksCreateCmd(flags))
	cmd.AddCommand(newSubtasksDeleteCmd(flags))
	cmd.AddCommand(newSubtasksGetCmd(flags))
	cmd.AddCommand(newSubtasksListCmd(flags))
	cmd.AddCommand(newSubtasksUpdateCmd(flags))
	return cmd
}
