// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTaskStatusesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "task-statuses",
		Short:  "Operations on task statuses",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTaskStatusesCreateCmd(flags))
	cmd.AddCommand(newTaskStatusesDeleteCmd(flags))
	cmd.AddCommand(newTaskStatusesGetCmd(flags))
	cmd.AddCommand(newTaskStatusesListCmd(flags))
	cmd.AddCommand(newTaskStatusesUpdateCmd(flags))
	return cmd
}
