// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "transactions",
		Short:  "Operations on transactions",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsCreateCmd(flags))
	cmd.AddCommand(newTransactionsGetCmd(flags))
	cmd.AddCommand(newTransactionsListCmd(flags))
	return cmd
}
