// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "search", Description: "Sub-100ms offline full-text search across contacts, matters, notes, comments, and interactions including custom fields.", Group: "Local state that compounds", WhyItMatters: "Reach for this instead of the API when an agent needs cross-entity search by free text."},
	{Command: "bottleneck", Description: "Median matter dwell-time per intake/pipeline stage, surfacing where deals get stuck.", Group: "Local state that compounds", WhyItMatters: "Use to answer 'where are matters dying?' without exporting CSVs."},
	{Command: "overdue", Description: "Every past-due task across every matter, grouped by assignee and sorted by lateness.", Group: "Local state that compounds", WhyItMatters: "Standup-ready workload view the Lawmatics UI cannot produce in one click."},
	{Command: "since", Description: "Everything created or updated in the last N hours/days across all entities.", Group: "Local state that compounds", WhyItMatters: "Intake-team standup view: what did we touch yesterday?"},
	{Command: "cf report", Description: "Join contacts and matters with arbitrary custom fields and pivot to CSV/JSON.", Group: "Local state that compounds", WhyItMatters: "Use when the firm needs ad-hoc analytics the web UI's report builder cannot do."},
	{Command: "bulk reassign", Description: "Reassign every task matching a filter from one user to another in one command.", Group: "Bulk operations", WhyItMatters: "Use during attorney transitions or PTO coverage instead of clicking through hundreds of tasks."},
	{Command: "velocity", Description: "Rolling conversion rate (prospect to signed matter) per referral source with sparklines.", Group: "Local state that compounds", WhyItMatters: "Marketing ROI question the API answers only with raw lists."},
	{Command: "intake stale", Description: "Prospects with zero interactions in N days.", Group: "Local state that compounds", WhyItMatters: "Surfaces leads that are about to die."},
	{Command: "who-touched", Description: "Unified chronological feed of every interaction, note, task, and email across all matters for a contact.", Group: "Local state that compounds", WhyItMatters: "Use before a re-engagement call or status meeting."},
	{Command: "revenue", Description: "Sums invoiced and paid amounts per referral source or practice area.", Group: "Local state that compounds", WhyItMatters: "Real marketing-channel ROI in one call."},
	{Command: "load", Description: "Open matters, overdue tasks, and billable hours MTD per attorney.", Group: "Local state that compounds", WhyItMatters: "Workload balancing in one command."},
	{Command: "doctor", Description: "Health check: orphan tasks, contacts with no email, matters in dead stages, custom fields never used, dormant users.", Group: "Agent-native plumbing", WhyItMatters: "Run quarterly to keep the firm's CRM data clean."},
	{Command: "watch", Description: "Local daemon that polls and POSTs entity diffs to a URL of your choice.", Group: "Agent-native plumbing", WhyItMatters: "Use when integrating Lawmatics with internal automation without paying for native webhooks."},
	{Command: "explain", Description: "Markdown brief summarizing a matter from notes, interactions, and tasks.", Group: "Local state that compounds", WhyItMatters: "Use before a status call to brief in 5 seconds."},
	{Command: "pipeline drift", Description: "Matters that skipped a stage or moved backward through the pipeline.", Group: "Local state that compounds", WhyItMatters: "Use to find broken intake processes before clients notice."},
	{Command: "forms fields", Description: "Flatten a custom form into its fillable field ids, labels, types, and required flags.", Group: "Custom forms", WhyItMatters: "The only way to learn a form's submit keys; the API returns name and timestamps unless fields=all is sent."},
	{Command: "forms submit", Description: "Create a custom form entry from a JSON body or repeated field assignments.", Group: "Custom forms", WhyItMatters: "Fill an intake form end to end from a script; submitting fires the form's automations."},
	{Command: "forms list", Description: "List every custom form on the account with its uuid and name.", Group: "Custom forms", WhyItMatters: "Resolve a form number like 0450 to the uuid every other forms command takes."},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  lawmatics-pp-cli which "stale tickets"
  lawmatics-pp-cli which "bottleneck"
  lawmatics-pp-cli which --limit 1 "send message"
  lawmatics-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
